site_name: RADON Framework for IaC Defect Prediction
repo_name: GitHub
repo_url: https://github.com/radon-h2020/radon-defect-prediction-api/
nav:
    - Getting Started: 
        - Quick Start: index.md
        - Features:
            - mine-github: mine_github
            - mine-repository: mine_reporitory
            - repositories: repositories
    - About: about.md
theme: readthedocs